# These are supported funding model platforms

# GitHub Sponsors 审核通过后取消下行注释即可:
# github: [yxxbc]

custom: ["https://github.com/yxxbc/mac-guide#%EF%B8%8F-%E8%B5%9E%E8%B5%8F%E4%B8%8E%E6%94%AF%E6%8C%81-sponsor"]
